sonar.projectKey=ontracker
sonar.projectName=Ontracker
sonar.sources=.
sonar.exclusions=venv/**,Ontrack/**,**/__pycache__/**,extension/node_modules/**,scripts/migrations/**,test-results.xml
sonar.python.version=3.11
sonar.python.xunit.reportPath=test-results.xml
